### ISSUE TITLE
Make main navigation more readable

### ISSUE THREAD

**Issue by herschel666** [jsunconf/2019.jsunconf.eu#24]
The main nav is currently hard to grasp for visitors.

- Imho the item `Make it…` can be removed completely.
- The item `Reduce, reuse,…` should be renamed to `Motto` in order to save space & make the appearance more consistent (no arbitrary horizontal ellipsis).

**Comment by JonasASchmidt** [comment]
https://github.com/jsunconf/2019.jsunconf.eu/pull/30
