### ISSUE TITLE
Make text on images better readable

### ISSUE THREAD

**Issue by herschel666** [jsunconf/2019.jsunconf.eu#25]
The current solution is hard to read & thus a critical issue from an `#a11y` point of view.

**Comment by JonasASchmidt** [comment]
I would suggest to put a gradient onto the iamges. Just di not know how to do that in PUG/JADE.

Something like this:

.class {
    background-image: linear-gradient(29deg, var(--darkish-purple), #0b66b2 85%, var(--ocean-blue));
}

Where:

:root {
    --darkish-purple: #911c80;
    --darkish-purple-alpha: rgba(145,28,128,0.75);
    --ocean-blue: #0669b4;
    --ocean-blue-alpha: rgba(6,105,180,0.75);
    --peacock-blue: #024b9f;
    --white: #fff;
    --black: #000;
    --dark-plum: #46003c;
}

**Comment by JonasASchmidt** [comment]
Added gradients to images. Done: https://github.com/jsunconf/2019.jsunconf.eu/pull/33
