### ISSUE TITLE
Update the preview image for https://2019.jsunconf.eu/

### ISSUE THREAD

**Issue by klyrr** [jsunconf/2019.jsunconf.eu#26]
![Screenshot 2019-03-13 at 11 18 48](https://user-images.githubusercontent.com/1024500/54273223-b881ec00-4585-11e9-8197-418983ae7a46.png)

The current preview still shows the old design. In order to align with the current layout we should update the preview image.

**Comment by JonasASchmidt** [comment]
Done with: https://github.com/jsunconf/2019.jsunconf.eu/pull/32
