### ISSUE TITLE
Tweak website performance

### ISSUE THREAD

**Issue by JonasASchmidt** [jsunconf/2019.jsunconf.eu#36]
According to: https://2019.jsconf.eu/news/how-we-built-the-fastest-conference-website-in-the-world/

**Comment by herschel666** [comment]
closing this for now.

<img width="880" alt="lighthouse results of 2019.jsunconf.eu" src="https://user-images.githubusercontent.com/520258/55425345-8e1ebf80-5582-11e9-870f-37bbe7ee2c01.png">
